
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanservice
  labels:
    app: loanservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loanservice
    spec:
      containers:
        - name: loanservice 
          image: docker.io/chenjigaramnaveen/loansservice
          ports:
          - containerPort: 1994
  selector:
    matchLabels:
      app: loanservice
---

apiVersion: v1
kind: Service
metadata:
    name: loanservice
    labels:
      app: loanservice
spec:
    type: LoadBalancer
    ports:
    - port: 1994
    selector:
        app: loanservice
